#!/usr/bin/python3

# Author: Matthias Maderer
# E-Mail: edvler@edvler-blog.de
# URL: https://github.com/edvler/check_mk_urbackup-check
# License: GPLv2

import urbackup_api
import configparser
import time
import os

#convert linux-time to timestamp
def unixTimeStampToDate(unix_stamp):
    return time.localtime(unix_stamp)

#read login config
conf_path = None
try:
   conf_path = os.environ['MK_CONFDIR']
except KeyError:
   conf_path = '/etc/check_mk'

config = configparser.ConfigParser()
config.read(conf_path + '/urbackup-check.ini')

url = config.get('server', 'url')
user = config.get('server', 'user')
password = config.get('server', 'password')

#connect string
server = urbackup_api.urbackup_server(url, user, password)

#query client infos
clients = server.get_status()

#Example string from api
#{'os_version_string': 'Microsoft Windows 7 Professional Service Pack 1 (build 7601), 32-Bit', 'groupname': '', 'os_simple': 'windows', 'online': False, 'ip': '-', 'name': 'FMT-PC', 'lastbackup_image': 0, 'delete_pending': '', 'last_filebackup_issues': 0, 'file_ok': False, 'lastseen': 1518290865, 'processes': [], 'status': 0, 'image_ok': False, 'id': 9, 'client_version_string': '2.1.17', 'lastbackup': 0}

#generate output for check_mk
print ('<<<urbackup-check>>>')
for client in clients:
    
    #Check if no backup exists
    if client["lastbackup"] == 0:
        filestamp_conv='-'
    else:
        filestamp_conv=time.strftime('%Y-%m-%d_%H:%M', unixTimeStampToDate(client["lastbackup"]))

    if client["lastbackup_image"] == 0:
        imagestamp_conv='-'
    else:
        imagestamp_conv=time.strftime('%Y-%m-%d_%H:%M', unixTimeStampToDate(client["lastbackup_image"]))

    #Print infos
    print ("{name};;;;;{filestamp};;;;;{fileok};;;;;{imagestamp};;;;;{imageok}".format(
           name=client["name"], 
           filestamp=filestamp_conv,
           imagestamp=imagestamp_conv,
           fileok=client["file_ok"],
           imageok=client["image_ok"],
           ))


